name: bodar_parivar_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  gap: ^3.0.1
  photo_view: ^0.15.0
  dio: ^5.7.0
  http: ^1.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:  
    - assets/images/

